// ----
// ---- file   : modular_env_analog_1.cpp
// ---- author : bsp
// ---- legal  : Distributed under terms of the MIT license (https://opensource.org/licenses/MIT)
// ----
// ----          Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
// ----          associated documentation files (the "Software"), to deal in the Software without restriction, including
// ----          without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// ----          copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to
// ----          the following conditions:
// ----
// ----          The above copyright notice and this permission notice shall be included in all copies or substantial
// ----          portions of the Software.
// ----
// ----          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
// ----          NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// ----          IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// ----          WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// ----          SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// ----
// ---- info   : auto-generated by "Cycle"
// ----           $ g++ -Wall -Wno-unused-function -Wno-unused-variable -I../../tksampler -c modular_env_analog_1.cpp -o modular_env_analog_1.o
// ---- created: 12Nov2024 00:44:40
// ----
// ----
// ----

// (note) pre-define CYCLE_SKIP_UI to skip all code used only for UI/editing purposes (e.g. when compiling for standalone replay)
// #define CYCLE_SKIP_UI  defined

#include <plugin.h>

#include <stdlib.h>
#include <math.h>
#include <string.h>

#define PARAM_A                  0
#define PARAM_ASHAPE             1
#define PARAM_D                  2
#define PARAM_DSHAPE             3
#define PARAM_S                  4
#define PARAM_R                  5
#define PARAM_RSHAPE             6
#define PARAM_SHAPE_AMT          7
#define NUM_PARAMS               8
#ifndef CYCLE_SKIP_UI
static const char *loc_param_names[NUM_PARAMS] = {
   "a",                       // 0: A
   "ashape",                  // 1: ASHAPE
   "d",                       // 2: D
   "dshape",                  // 3: DSHAPE
   "s",                       // 4: S
   "r",                       // 5: R
   "rshape",                  // 6: RSHAPE
   "shape_amt",               // 7: SHAPE_AMT

};
#endif // CYCLE_SKIP_UI
static float loc_param_resets[NUM_PARAMS] = {
   1.0f,                      // 0: A
   0.5f,                      // 1: ASHAPE
   0.3f,                      // 2: D
   0.5f,                      // 3: DSHAPE
   0.6f,                      // 4: S
   0.1f,                      // 5: R
   0.5f,                      // 6: RSHAPE
   0.5f,                      // 7: SHAPE_AMT

};

#define MOD_GATE                 0
#define MOD_A                    1
#define MOD_ASHAPE               2
#define MOD_D                    3
#define MOD_S                    4
#define MOD_R                    5
#define MOD_DR_SHAPE             6
#define MOD_SHAPE_AMT            7
#define NUM_MODS                 8
#ifndef CYCLE_SKIP_UI
static const char *loc_mod_names[NUM_MODS] = {
   "gate",                 // 0: GATE
   "a",                    // 1: A
   "ashape",               // 2: ASHAPE
   "d",                    // 3: D
   "s",                    // 4: S
   "r",                    // 5: R
   "dr_shape",             // 6: DR_SHAPE
   "shape_amt",            // 7: SHAPE_AMT

};
#endif // CYCLE_SKIP_UI

typedef struct modular_env_analog_1_info_s {
   st_plugin_info_t base;
} modular_env_analog_1_info_t;

typedef struct modular_env_analog_1_shared_s {
   st_plugin_shared_t base;
   float params[NUM_PARAMS];

} modular_env_analog_1_shared_t;

typedef struct modular_env_analog_1_voice_s {
   st_plugin_voice_t base;
   float             sample_rate;
   float             bpm;
   float             velocity;
   float             note_speed_fixed;
   float             note_speed_cur;
   float             note_speed_inc;
   float             note_cur;
   float             note_inc;
   float             mods[NUM_MODS];
   float mod_gate_cur;
   float mod_gate_inc;
   float mod_a_cur;
   float mod_a_inc;
   float mod_ashape_cur;
   float mod_ashape_inc;
   float mod_d_cur;
   float mod_d_inc;
   float mod_s_cur;
   float mod_s_inc;
   float mod_r_cur;
   float mod_r_inc;
   float mod_dr_shape_cur;
   float mod_dr_shape_inc;
   float mod_shape_amt_cur;
   float mod_shape_amt_inc;

   float tmp1_adsrv1_last_gate;
   float tmp2_adsrv1_levelint;
   float tmp3_adsrv1_level;
   float tmp4_adsrv1_vel;
   float tmp5_adsrv1_last_sus_level;
   float tmp6_adsrv1_last_atk_level;
   short tmp7_adsrv1_segidx;
   float tmp8;
   float tmp9;
   float tmp10;
   float tmp11;
   float tmp12;
   float tmp13;
   short tmp14;
   short tmp15;
   float var_x;
   float sr_factor;
   float add_sr_0;  // 0.03f

} modular_env_analog_1_voice_t;

#define loop(X)  for(unsigned int i = 0u; i < (X); i++)
#define clamp(a,b,c) (((a)<(b))?(b):(((a)>(c))?(c):(a)))

static inline float mathLerpf(float _a, float _b, float _t) { return _a + (_b - _a) * _t; }
static inline float mathClampf(float a, float b, float c) { return (((a)<(b))?(b):(((a)>(c))?(c):(a))); }
static inline float mathMinf(float a, float b) { return (a<b)?a:b; }
static inline float mathMaxf(float a, float b) { return (a>b)?a:b; }
static inline float mathAbsMaxf(float _x, float _y) { return ( ( (_x<0.0f)?-_x:_x)>((_y<0.0f)?-_y:_y)?_x:_y ); }
static inline float mathAbsMinf(float _x, float _y) { return ( ((_x<0.0f)?-_x:_x)<((_y<0.0f)?-_y:_y)?_x:_y ); }
static inline float frac(float _x) { return _x - ((int)_x); }

static inline float winLinear(const float *_s, float _index) {
   int idx = (int)_index;
   float r = _index - (float)idx;
   return mathLerpf(_s[idx], _s[idx+1], r);
}

static float ffrac_s(float _f) { int i; if(_f >= 0.0f) { i = (int)_f; return _f - (float)i; } else { i = (int)-_f; return 1.0f - (-_f - (float)i); } }
static short curve_0[4096] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 
13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 
15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 
20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 
23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 
26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 
29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32, 
32, 32, 32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 35, 
35, 35, 35, 35, 35, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 37, 37, 37, 37, 37, 37, 37, 37, 38, 38, 38, 38, 38, 38, 38, 
38, 38, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40, 40, 40, 40, 40, 40, 40, 40, 40, 41, 41, 41, 41, 41, 41, 41, 41, 41, 42, 42, 
42, 42, 42, 42, 42, 42, 42, 43, 43, 43, 43, 43, 43, 43, 43, 43, 44, 44, 44, 44, 44, 44, 44, 44, 45, 45, 45, 45, 45, 45, 45, 45, 
45, 46, 46, 46, 46, 46, 46, 46, 46, 46, 47, 47, 47, 47, 47, 47, 47, 47, 48, 48, 48, 48, 48, 48, 48, 48, 49, 49, 49, 49, 49, 49, 
49, 49, 49, 50, 50, 50, 50, 50, 50, 50, 50, 51, 51, 51, 51, 51, 51, 51, 51, 52, 52, 52, 52, 52, 52, 52, 52, 53, 53, 53, 53, 53, 
53, 53, 53, 54, 54, 54, 54, 54, 54, 54, 54, 55, 55, 55, 55, 55, 55, 55, 55, 56, 56, 56, 56, 56, 56, 56, 56, 57, 57, 57, 57, 57, 
57, 57, 57, 58, 58, 58, 58, 58, 58, 58, 59, 59, 59, 59, 59, 59, 59, 59, 60, 60, 60, 60, 60, 60, 60, 60, 61, 61, 61, 61, 61, 61, 
61, 62, 62, 62, 62, 62, 62, 62, 62, 63, 63, 63, 63, 63, 63, 63, 64, 64, 64, 64, 64, 64, 64, 65, 65, 65, 65, 65, 65, 65, 65, 66, 
66, 66, 66, 66, 66, 66, 67, 67, 67, 67, 67, 67, 67, 68, 68, 68, 68, 68, 68, 68, 69, 69, 69, 69, 69, 69, 69, 70, 70, 70, 70, 70, 
70, 70, 71, 71, 71, 71, 71, 71, 71, 72, 72, 72, 72, 72, 72, 72, 73, 73, 73, 73, 73, 73, 73, 74, 74, 74, 74, 74, 74, 74, 75, 75, 
75, 75, 75, 75, 75, 76, 76, 76, 76, 76, 76, 76, 77, 77, 77, 77, 77, 77, 77, 78, 78, 78, 78, 78, 78, 79, 79, 79, 79, 79, 79, 79, 
80, 80, 80, 80, 80, 80, 81, 81, 81, 81, 81, 81, 81, 82, 82, 82, 82, 82, 82, 82, 83, 83, 83, 83, 83, 83, 84, 84, 84, 84, 84, 84, 
85, 85, 85, 85, 85, 85, 85, 86, 86, 86, 86, 86, 86, 87, 87, 87, 87, 87, 87, 87, 88, 88, 88, 88, 88, 88, 89, 89, 89, 89, 89, 89, 
90, 90, 90, 90, 90, 90, 91, 91, 91, 91, 91, 91, 91, 92, 92, 92, 92, 92, 92, 93, 93, 93, 93, 93, 93, 94, 94, 94, 94, 94, 94, 95, 
95, 95, 95, 95, 95, 96, 96, 96, 96, 96, 96, 97, 97, 97, 97, 97, 97, 98, 98, 98, 98, 98, 98, 99, 99, 99, 99, 99, 99, 100, 100, 100, 
100, 100, 100, 101, 101, 101, 101, 101, 101, 102, 102, 102, 102, 102, 103, 103, 103, 103, 103, 103, 104, 104, 104, 104, 104, 104, 105, 105, 105, 105, 105, 105, 
106, 106, 106, 106, 106, 106, 107, 107, 107, 107, 107, 108, 108, 108, 108, 108, 108, 109, 109, 109, 109, 109, 109, 110, 110, 110, 110, 110, 111, 111, 111, 111, 
111, 111, 112, 112, 112, 112, 112, 113, 113, 113, 113, 113, 113, 114, 114, 114, 114, 114, 115, 115, 115, 115, 115, 115, 116, 116, 116, 116, 116, 117, 117, 117, 
117, 117, 117, 118, 118, 118, 118, 118, 119, 119, 119, 119, 119, 119, 120, 120, 120, 120, 120, 121, 121, 121, 121, 121, 122, 122, 122, 122, 122, 122, 123, 123, 
123, 123, 123, 124, 124, 124, 124, 124, 125, 125, 125, 125, 125, 126, 126, 126, 126, 126, 126, 127, 127, 127, 127, 127, 128, 128, 128, 128, 128, 129, 129, 129, 
129, 129, 130, 130, 130, 130, 130, 131, 131, 131, 131, 131, 131, 132, 132, 132, 132, 132, 133, 133, 133, 133, 133, 134, 134, 134, 134, 134, 135, 135, 135, 135, 
135, 136, 136, 136, 136, 136, 137, 137, 137, 137, 137, 138, 138, 138, 138, 138, 139, 139, 139, 139, 139, 140, 140, 140, 140, 140, 141, 141, 141, 141, 141, 142, 
142, 142, 142, 142, 143, 143, 143, 143, 144, 144, 144, 144, 144, 145, 145, 145, 145, 145, 146, 146, 146, 146, 146, 147, 147, 147, 147, 147, 148, 148, 148, 148, 
148, 149, 149, 149, 149, 150, 150, 150, 150, 150, 151, 151, 151, 151, 151, 152, 152, 152, 152, 152, 153, 153, 153, 153, 154, 154, 154, 154, 154, 155, 155, 155, 
155, 155, 156, 156, 156, 156, 157, 157, 157, 157, 157, 158, 158, 158, 158, 158, 159, 159, 159, 159, 160, 160, 160, 160, 160, 161, 161, 161, 161, 162, 162, 162, 
162, 162, 163, 163, 163, 163, 164, 164, 164, 164, 164, 165, 165, 165, 165, 165, 166, 166, 166, 166, 167, 167, 167, 167, 168, 168, 168, 168, 168, 169, 169, 169, 
169, 170, 170, 170, 170, 170, 171, 171, 171, 171, 172, 172, 172, 172, 172, 173, 173, 173, 173, 174, 174, 174, 174, 175, 175, 175, 175, 175, 176, 176, 176, 176, 
177, 177, 177, 177, 177, 178, 178, 178, 178, 179, 179, 179, 179, 180, 180, 180, 180, 181, 181, 181, 181, 181, 182, 182, 182, 182, 183, 183, 183, 183, 184, 184, 
184, 184, 184, 185, 185, 185, 185, 186, 186, 186, 186, 187, 187, 187, 187, 188, 188, 188, 188, 189, 189, 189, 189, 189, 190, 190, 190, 190, 191, 191, 191, 191, 
192, 192, 192, 192, 193, 193, 193, 193, 194, 194, 194, 194, 195, 195, 195, 195, 196, 196, 196, 196, 196, 197, 197, 197, 197, 198, 198, 198, 198, 199, 199, 199, 
199, 200, 200, 200, 200, 201, 201, 201, 201, 202, 202, 202, 202, 203, 203, 203, 203, 204, 204, 204, 204, 205, 205, 205, 205, 206, 206, 206, 206, 207, 207, 207, 
207, 208, 208, 208, 208, 209, 209, 209, 209, 210, 210, 210, 210, 211, 211, 211, 211, 212, 212, 212, 213, 213, 213, 213, 214, 214, 214, 214, 215, 215, 215, 215, 
216, 216, 216, 216, 217, 217, 217, 217, 218, 218, 218, 218, 219, 219, 219, 219, 220, 220, 220, 221, 221, 221, 221, 222, 222, 222, 222, 223, 223, 223, 223, 224, 
224, 224, 224, 225, 225, 225, 226, 226, 226, 226, 227, 227, 227, 227, 228, 228, 228, 228, 229, 229, 229, 230, 230, 230, 230, 231, 231, 231, 231, 232, 232, 232, 
232, 233, 233, 233, 234, 234, 234, 234, 235, 235, 235, 235, 236, 236, 236, 237, 237, 237, 237, 238, 238, 238, 238, 239, 239, 239, 240, 240, 240, 240, 241, 241, 
241, 241, 242, 242, 242, 243, 243, 243, 243, 244, 244, 244, 245, 245, 245, 245, 246, 246, 246, 246, 247, 247, 247, 248, 248, 248, 248, 249, 249, 249, 250, 250, 
250, 250, 251, 251, 251, 252, 252, 252, 252, 253, 253, 253, 254, 254, 254, 254, 255, 255, 255, 256, 256, 256, 256, 257, 257, 257, 258, 258, 258, 258, 259, 259, 
259, 260, 260, 260, 260, 261, 261, 261, 262, 262, 262, 262, 263, 263, 263, 264, 264, 264, 264, 265, 265, 265, 266, 266, 266, 267, 267, 267, 267, 268, 268, 268, 
269, 269, 269, 269, 270, 270, 270, 271, 271, 271, 272, 272, 272, 272, 273, 273, 273, 274, 274, 274, 275, 275, 275, 275, 276, 276, 276, 277, 277, 277, 278, 278, 
278, 278, 279, 279, 279, 280, 280, 280, 281, 281, 281, 281, 282, 282, 282, 283, 283, 283, 284, 284, 284, 285, 285, 285, 285, 286, 286, 286, 287, 287, 287, 288, 
288, 288, 288, 289, 289, 289, 290, 290, 290, 291, 291, 291, 292, 292, 292, 293, 293, 293, 293, 294, 294, 294, 295, 295, 295, 296, 296, 296, 297, 297, 297, 298, 
298, 298, 298, 299, 299, 299, 300, 300, 300, 301, 301, 301, 302, 302, 302, 303, 303, 303, 304, 304, 304, 304, 305, 305, 305, 306, 306, 306, 307, 307, 307, 308, 
308, 308, 309, 309, 309, 310, 310, 310, 311, 311, 311, 312, 312, 312, 313, 313, 313, 314, 314, 314, 315, 315, 315, 315, 316, 316, 316, 317, 317, 317, 318, 318, 
318, 319, 319, 319, 320, 320, 320, 321, 321, 321, 322, 322, 322, 323, 323, 323, 324, 324, 324, 325, 325, 325, 326, 326, 326, 327, 327, 327, 328, 328, 328, 329, 
329, 329, 330, 330, 330, 331, 331, 331, 332, 332, 332, 333, 333, 333, 334, 334, 334, 335, 335, 335, 336, 336, 337, 337, 337, 338, 338, 338, 339, 339, 339, 340, 
340, 340, 341, 341, 341, 342, 342, 342, 343, 343, 343, 344, 344, 344, 345, 345, 345, 346, 346, 347, 347, 347, 348, 348, 348, 349, 349, 349, 350, 350, 350, 351, 
351, 351, 352, 352, 352, 353, 353, 354, 354, 354, 355, 355, 355, 356, 356, 356, 357, 357, 357, 358, 358, 358, 359, 359, 360, 360, 360, 361, 361, 361, 362, 362, 
362, 363, 363, 363, 364, 364, 365, 365, 365, 366, 366, 366, 367, 367, 367, 368, 368, 369, 369, 369, 370, 370, 370, 371, 371, 371, 372, 372, 373, 373, 373, 374, 
374, 374, 375, 375, 376, 376, 376, 377, 377, 377, 378, 378, 378, 379, 379, 380, 380, 380, 381, 381, 381, 382, 382, 383, 383, 383, 384, 384, 384, 385, 385, 386, 
386, 386, 387, 387, 387, 388, 388, 389, 389, 389, 390, 390, 390, 391, 391, 392, 392, 392, 393, 393, 393, 394, 394, 395, 395, 395, 396, 396, 397, 397, 397, 398, 
398, 398, 399, 399, 400, 400, 400, 401, 401, 402, 402, 402, 403, 403, 403, 404, 404, 405, 405, 405, 406, 406, 407, 407, 407, 408, 408, 409, 409, 409, 410, 410, 
410, 411, 411, 412, 412, 412, 413, 413, 414, 414, 414, 415, 415, 416, 416, 416, 417, 417, 418, 418, 418, 419, 419, 420, 420, 420, 421, 421, 422, 422, 422, 423, 
423, 424, 424, 424, 425, 425, 426, 426, 426, 427, 427, 428, 428, 428, 429, 429, 430, 430, 431, 431, 431, 432, 432, 433, 433, 433, 434, 434, 435, 435, 435, 436, 
436, 437, 437, 437, 438, 438, 439, 439, 440, 440, 440, 441, 441, 442, 442, 442, 443, 443, 444, 444, 445, 445, 445, 446, 446, 447, 447, 448, 448, 448, 449, 449, 
450, 450, 450, 451, 451, 452, 452, 453, 453, 453, 454, 454, 455, 455, 456, 456, 456, 457, 457, 458, 458, 459, 459, 459, 460, 460, 461, 461, 462, 462, 462, 463, 
463, 464, 464, 465, 465, 466, 466, 466, 467, 467, 468, 468, 469, 469, 469, 470, 470, 471, 471, 472, 472, 473, 473, 473, 474, 474, 475, 475, 476, 476, 477, 477, 
477, 478, 478, 479, 479, 480, 480, 481, 481, 481, 482, 482, 483, 483, 484, 484, 485, 485, 485, 486, 486, 487, 487, 488, 488, 489, 489, 490, 490, 490, 491, 491, 
492, 492, 493, 493, 494, 494, 495, 495, 496, 496, 496, 497, 497, 498, 498, 499, 499, 500, 500, 501, 501, 502, 502, 502, 503, 503, 504, 504, 505, 505, 506, 506, 
507, 507, 508, 508, 509, 509, 510, 510, 510, 511, 511, 512, 512, 513, 513, 514, 514, 515, 515, 516, 516, 517, 517, 518, 518, 519, 519, 520, 520, 521, 521, 521, 
522, 522, 523, 523, 524, 524, 525, 525, 526, 526, 527, 527, 528, 528, 529, 529, 530, 530, 531, 531, 532, 532, 533, 533, 534, 534, 535, 535, 536, 536, 537, 537, 
538, 538, 539, 539, 540, 540, 541, 541, 542, 542, 543, 543, 544, 544, 545, 545, 546, 546, 547, 547, 548, 548, 549, 549, 550, 550, 551, 551, 552, 552, 553, 553, 
554, 554, 555, 555, 556, 556, 557, 557, 558, 558, 559, 559, 560, 560, 561, 561, 562, 563, 563, 564, 564, 565, 565, 566, 566, 567, 567, 568, 568, 569, 569, 570, 
570, 571, 571, 572, 572, 573, 574, 574, 575, 575, 576, 576, 577, 577, 578, 578, 579, 579, 580, 580, 581, 582, 582, 583, 583, 584, 584, 585, 585, 586, 586, 587, 
587, 588, 589, 589, 590, 590, 591, 591, 592, 592, 593, 593, 594, 595, 595, 596, 596, 597, 597, 598, 598, 599, 599, 600, 601, 601, 602, 602, 603, 603, 604, 604, 
605, 606, 606, 607, 607, 608, 608, 609, 609, 610, 611, 611, 612, 612, 613, 613, 614, 615, 615, 616, 616, 617, 617, 618, 619, 619, 620, 620, 621, 621, 622, 623, 
623, 624, 624, 625, 625, 626, 627, 627, 628, 628, 629, 629, 630, 631, 631, 632, 632, 633, 634, 634, 635, 635, 636, 636, 637, 638, 638, 639, 639, 640, 641, 641, 
642, 642, 643, 643, 644, 645, 645, 646, 646, 647, 648, 648, 649, 649, 650, 651, 651, 652, 652, 653, 654, 654, 655, 655, 656, 657, 657, 658, 658, 659, 660, 660, 
661, 661, 662, 663, 663, 664, 664, 665, 666, 666, 667, 668, 668, 669, 669, 670, 671, 671, 672, 672, 673, 674, 674, 675, 676, 676, 677, 677, 678, 679, 679, 680, 
680, 681, 682, 682, 683, 684, 684, 685, 686, 686, 687, 687, 688, 689, 689, 690, 691, 691, 692, 692, 693, 694, 694, 695, 696, 696, 697, 698, 698, 699, 699, 700, 
701, 701, 702, 703, 703, 704, 705, 705, 706, 706, 707, 708, 708, 709, 710, 710, 711, 712, 712, 713, 714, 714, 715, 716, 716, 717, 718, 718, 719, 719, 720, 721, 
721, 722, 723, 723, 724, 725, 725, 726, 727, 727, 728, 729, 729, 730, 731, 731, 732, 733, 733, 734, 735, 735, 736, 737, 737, 738, 739, 739, 740, 741, 741, 742, 
743, 743, 744, 745, 745, 746, 747, 747, 748, 749, 750, 750, 751, 752, 752, 753, 754, 754, 755, 756, 756, 757, 758, 758, 759, 760, 760, 761, 762, 763, 763, 764, 
765, 765, 766, 767, 767, 768, 769, 769, 770, 771, 772, 772, 773, 774, 774, 775, 776, 776, 777, 778, 778, 779, 780, 781, 781, 782, 783, 783, 784, 785, 786, 786, 
787, 788, 788, 789, 790, 790, 791, 792, 793, 793, 794, 795, 795, 796, 797, 798, 798, 799, 800, 800, 801, 802, 803, 803, 804, 805, 805, 806, 807, 808, 808, 809, 
810, 811, 811, 812, 813, 813, 814, 815, 816, 816, 817, 818, 818, 819, 820, 821, 821, 822, 823, 824, 824, 825, 826, 827, 827, 828, 829, 829, 830, 831, 832, 832, 
833, 834, 835, 835, 836, 837, 838, 838, 839, 840, 841, 841, 842, 843, 844, 844, 845, 846, 846, 847, 848, 849, 849, 850, 851, 852, 852, 853, 854, 855, 855, 856, 
857, 858, 858, 859, 860, 861, 861, 862, 863, 864, 865, 865, 866, 867, 868, 868, 869, 870, 871, 871, 872, 873, 874, 874, 875, 876, 877, 877, 878, 879, 880, 880, 
881, 882, 883, 884, 884, 885, 886, 887, 887, 888, 889, 890, 890, 891, 892, 893, 894, 894, 895, 896, 897, 897, 898, 899, 900, 900, 901, 902, 903, 904, 904, 905, 
906, 907, 907, 908, 909, 910, 911, 911, 912, 913, 914, 915, 915, 916, 917, 918, 918, 919, 920, 921, 922, 922, 923, 924, 925, 926, 926, 927, 928, 929, 929, 930, 
931, 932, 933, 934, 934, 935, 936, 937, 938, 938, 939, 940, 941, 942, 943, 943, 944, 945, 946, 947, 948, 948, 949, 950, 951, 952, 953, 954, 954, 955, 956, 957, 
958, 959, 960, 960, 961, 962, 963, 964, 965, 966, 967, 968, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 
987, 988, 989, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 
1018, 1018, 1019, 1020, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 
1050, 1051, 1052, 1053, 1054, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1082, 1083, 1084, 
1085, 1086, 1087, 1088, 1089, 1090, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1117, 1118, 1119, 1120, 
1121, 1122, 1124, 1125, 1126, 1127, 1128, 1129, 1131, 1132, 1133, 1134, 1135, 1136, 1138, 1139, 1140, 1141, 1142, 1144, 1145, 1146, 1147, 1148, 1150, 1151, 1152, 1153, 1154, 1156, 1157, 1158, 
1159, 1160, 1162, 1163, 1164, 1165, 1167, 1168, 1169, 1170, 1171, 1173, 1174, 1175, 1176, 1178, 1179, 1180, 1181, 1183, 1184, 1185, 1186, 1187, 1189, 1190, 1191, 1192, 1194, 1195, 1196, 1197, 
1199, 1200, 1201, 1202, 1204, 1205, 1206, 1208, 1209, 1210, 1211, 1213, 1214, 1215, 1216, 1218, 1219, 1220, 1221, 1223, 1224, 1225, 1227, 1228, 1229, 1230, 1232, 1233, 1234, 1236, 1237, 1238, 
1239, 1241, 1242, 1243, 1245, 1246, 1247, 1249, 1250, 1251, 1252, 1254, 1255, 1256, 1258, 1259, 1260, 1262, 1263, 1264, 1266, 1267, 1268, 1270, 1271, 1272, 1273, 1275, 1276, 1277, 1279, 1280, 
1281, 1283, 1284, 1285, 1287, 1288, 1289, 1291, 1292, 1293, 1295, 1296, 1297, 1299, 1300, 1301, 1303, 1304, 1305, 1307, 1308, 1309, 1311, 1312, 1314, 1315, 1316, 1318, 1319, 1320, 1322, 1323, 
1324, 1326, 1327, 1328, 1330, 1331, 1332, 1334, 1335, 1337, 1338, 1339, 1341, 1342, 1343, 1345, 1346, 1347, 1349, 1350, 1352, 1353, 1354, 1356, 1357, 1358, 1360, 1361, 1362, 1364, 1365, 1367, 
1368, 1369, 1371, 1372, 1373, 1375, 1376, 1378, 1379, 1380, 1382, 1383, 1384, 1386, 1387, 1389, 1390, 1391, 1393, 1394, 1395, 1397, 1398, 1400, 1401, 1402, 1404, 1405, 1407, 1408, 1409, 1411, 
1412, 1413, 1415, 1416, 1418, 1419, 1420, 1422, 1423, 1425, 1426, 1427, 1429, 1430, 1432, 1433, 1434, 1436, 1437, 1438, 1440, 1441, 1443, 1444, 1445, 1447, 1448, 1450, 1451, 1452, 1454, 1455, 
1457, 1458, 1459, 1461, 1462, 1463, 1465, 1466, 1468, 1469, 1470, 1472, 1473, 1475, 1476, 1477, 1479, 1480, 1482, 1483, 1484, 1486, 1487, 1488, 1490, 1491, 1493, 1494, 1495, 1497, 1498, 1500, 
1501, 1502, 1504, 1505, 1507, 1508, 1509, 1511, 1512, 1513, 1515, 1516, 1518, 1519, 1520, 1522, 1523, 1525, 1526, 1527, 1529, 1530, 1531, 1533, 1534, 1536, 1537, 1538, 1540, 1541, 1542, 1544, 
1545, 1547, 1548, 1549, 1551, 1552, 1553, 1555, 1556, 1558, 1559, 1560, 1562, 1563, 1564, 1566, 1567, 1569, 1570, 1571, 1573, 1574, 1575, 1577, 1578, 1580, 1581, 1582, 1584, 1585, 1586, 1588, 
1589, 1590, 1592, 1593, 1594, 1596, 1597, 1599, 1600, 1601, 1603, 1604, 1605, 1607, 1608, 1609, 1611, 1612, 1613, 1615, 1616, 1617, 1619, 1620, 1621, 1623, 1624, 1625, 1627, 1628, 1629, 1631, 
1632, 1633, 1635, 1636, 1637, 1639, 1640, 1641, 1643, 1644, 1645, 1647, 1648, 1649, 1651, 1652, 1653, 1655, 1656, 1657, 1659, 1660, 1661, 1662, 1664, 1665, 1666, 1668, 1669, 1670, 1672, 1673, 
1674, 1675, 1677, 1678, 1679, 1681, 1682, 1683, 1684, 1686, 1687, 1688, 1690, 1691, 1692, 1693, 1695, 1696, 1697, 1699, 1700, 1701, 1702, 1704, 1705, 1706, 1707, 1709, 1710, 1711, 1712, 1714, 
1715, 1716, 1718, 1719, 1720, 1721, 1723, 1724, 1725, 1726, 1727, 1729, 1730, 1731, 1732, 1734, 1735, 1736, 1737, 1739, 1740, 1741, 1742, 1743, 1745, 1746, 1747, 1748, 1750, 1751, 1752, 1753, 
1754, 1756, 1757, 1758, 1759, 1760, 1762, 1763, 1764, 1765, 1766, 1768, 1769, 1770, 1771, 1772, 1773, 1775, 1776, 1777, 1778, 1779, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1789, 1790, 1791, 
1792, 1793, 1794, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1824, 1825, 1826, 1827, 
1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1858, 1859, 1860, 1861, 
1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 
1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1919, 1920, 1921, 
1922, 1923, 1924, 1925, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1931, 1932, 1933, 1934, 1935, 1936, 1936, 1937, 1938, 1939, 1940, 1940, 1941, 1942, 1943, 1944, 1945, 1945, 1946, 1947, 1948, 
1948, 1949, 1950, 1951, 1952, 1952, 1953, 1954, 1955, 1955, 1956, 1957, 1958, 1958, 1959, 1960, 1961, 1961, 1962, 1963, 1964, 1964, 1965, 1966, 1967, 1967, 1968, 1969, 1969, 1970, 1971, 1972, 
1972, 1973, 1974, 1974, 1975, 1976, 1976, 1977, 1978, 1978, 1979, 1980, 1980, 1981, 1982, 1982, 1983, 1984, 1984, 1985, 1986, 1986, 1987, 1988, 1988, 1989, 1989, 1990, 1991, 1991, 1992, 1993, 
1993, 1994, 1994, 1995, 1996, 1996, 1997, 1997, 1998, 1999, 1999, 2000, 2000, 2001, 2001, 2002, 2003, 2003, 2004, 2004, 2005, 2005, 2006, 2006, 2007, 2008, 2008, 2009, 2009, 2010, 2010, 2011, 
2011, 2012, 2012, 2013, 2013, 2014, 2014, 2015, 2015, 2016, 2016, 2017, 2017, 2018, 2018, 2019, 2019, 2020, 2020, 2021, 2021, 2022, 2022, 2023, 2023, 2023, 2024, 2024, 2025, 2025, 2025, 2026, 
2026, 2027, 2027, 2028, 2028, 2028, 2029, 2029, 2030, 2030, 2031, 2031, 2031, 2032, 2032, 2032, 2033, 2033, 2034, 2034, 2034, 2035, 2035, 2035, 2036, 2036, 2037, 2037, 2037, 2038, 2038, 2038, 
2039, 2039, 2039, 2039, 2040, 2040, 2040, 2041, 2041, 2041, 2042, 2042, 2042, 2043, 2043, 2043, 2043, 2044, 2044, 2044, 2045, 2045, 2045, 2045, 2046, 2046, 2046, 2046, 2047, 2047, 2047, 2048, 
};

static float mathLogLinExpf(float _f, float _c) {
   // c: <0: log
   //     0: lin
   //    >0: exp
   stplugin_fi_t uSign;
   uSign.f = _f;
   stplugin_fi_t u;
   u.f = _f;
   u.u &= 0x7fffFFFFu;
   u.f = powf(u.f, powf(2.0f, _c));
   u.u |= uSign.u & 0x80000000u;
   return u.f;
}



#ifndef CYCLE_SKIP_UI
static unsigned int loc_copy_chars(char *_d, const unsigned int _dSize, const char *_s) {
   unsigned int r = 0u;
   if(NULL != _d)
   {
      // Write min(dSize,len(s)) characters to 'd'
      char *d = _d;
      if(NULL != _s)
      {
         const char *s = _s;
         for(;;)
         {
            if(r < _dSize)
            {
               char c = s[r++];
               *d++ = c;
               if(0 == c)
                  break;
            }
            else
            {
               if(r > 0u)
                  d[-1] = 0;  // force ASCIIZ
               break;
            }
         }
      }
      else
      {
         if(_dSize > 0u)
         {
            _d[0] = 0;
            r = 1u;
         }
      }
   }
   else
   {
      // Return total length of source string
      if(NULL != _s)
      {
         const char *s = _s;
         for(;;)
         {
            char c = s[r++];
            if(0 == c)
               break;
         }
      }
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int loc_copy_floats(float              *_d,
                                    const unsigned int  _dSize,
                                    const float        *_s,
                                    const unsigned int  _sNum
                                    ) {
   unsigned int r = 0u;
   if(NULL != _d)
   {
      // Write min(dSize,sNum) characters to 'd'
      if(NULL != _s)
      {
         unsigned int num = (_sNum > _dSize) ? _dSize : _sNum;
         memcpy((void*)_d, (const void*)_s, num * sizeof(float));
         r = num;
      }
   }
   else
   {
      // Query total number of presets
      r = _sNum;
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static const char *ST_PLUGIN_API loc_get_param_name(st_plugin_info_t *_info,
                                                    unsigned int      _paramIdx
                                                    ) {
   (void)_info;
   return loc_param_names[_paramIdx];
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static const char *ST_PLUGIN_API loc_get_param_group_name(st_plugin_info_t *_info,
                                                          unsigned int      _paramGroupIdx
                                                          ) {
   (void)_info;
   const char *r = NULL;
   static const char *groupNames[3] = { "rate", "shape", "level" };
   if(_paramGroupIdx < 3u)
      r = groupNames[_paramGroupIdx];
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_get_param_group_idx(st_plugin_info_t *_info,
                                                          unsigned int      _paramIdx
                                                          ) {
   (void)_info;
   unsigned int r = ~0u;
   static unsigned int groupIndices[NUM_PARAMS] = { 0, 1, 0, 1, 2, 0, 1, 1 };
   r = groupIndices[_paramIdx];
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static const char *ST_PLUGIN_API loc_get_param_section_name(st_plugin_info_t *_info,
                                                            unsigned int      _paramSectionIdx
                                                            ) {
   (void)_info;
   const char *r = NULL;
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_get_param_section_idx(st_plugin_info_t *_info,
                                                            unsigned int      _paramIdx
                                                            ) {
   (void)_info;
   unsigned int r = ~0u;
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static float ST_PLUGIN_API loc_get_param_reset(st_plugin_info_t *_info,
                                               unsigned int      _paramIdx
                                               ) {
   (void)_info;
   return loc_param_resets[_paramIdx];
}
#endif // CYCLE_SKIP_UI

static float ST_PLUGIN_API loc_get_param_value(st_plugin_shared_t *_shared,
                                               unsigned int        _paramIdx
                                               ) {
   ST_PLUGIN_SHARED_CAST(modular_env_analog_1_shared_t);
   return shared->params[_paramIdx];
}

static void ST_PLUGIN_API loc_set_param_value(st_plugin_shared_t *_shared,
                                              unsigned int        _paramIdx,
                                              float               _value
                                              ) {
   ST_PLUGIN_SHARED_CAST(modular_env_analog_1_shared_t);
   shared->params[_paramIdx] = _value;
}

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_query_dynamic_param_preset_values(st_plugin_shared_t *_shared,
                                                                        const unsigned int  _paramIdx,
                                                                        float              *_retValues,
                                                                        const unsigned int  _retValuesSize
                                                                        ) {
   ST_PLUGIN_SHARED_CAST(modular_env_analog_1_shared_t);
   unsigned int r = 0u;
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_query_dynamic_param_preset_name(st_plugin_shared_t *_shared,
                                                                      const unsigned int  _paramIdx,
                                                                      const unsigned int  _presetIdx,
                                                                      char               *_retBuf,
                                                                      const unsigned int  _retBufSize
                                                                      ) {
   ST_PLUGIN_SHARED_CAST(modular_env_analog_1_shared_t);
   unsigned int r = 0u;
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_get_array_param_size(st_plugin_info_t   *_info,
                                                           const unsigned int  _paramIdx
                                                           ) {
   unsigned int r = 0u;
   switch(_paramIdx)
   {
      default:
         break;
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static unsigned int ST_PLUGIN_API loc_get_array_param_num_variations(st_plugin_info_t   *_info,
                                                                     const unsigned int  _paramIdx
                                                                     ) {
   unsigned int r = 0u;
   switch(_paramIdx)
   {
      default:
         break;
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static float * ST_PLUGIN_API loc_get_array_param_variation_ptr(st_plugin_shared_t *_shared,
                                                               const unsigned int  _paramIdx,
                                                               const unsigned int  _variationIdx
                                                               ) {
   ST_PLUGIN_SHARED_CAST(modular_env_analog_1_shared_t);
   float *r = NULL;
   switch(_paramIdx)
   {
      default:
         break;
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static void ST_PLUGIN_API loc_set_array_param_edit_variation_idx(st_plugin_shared_t *_shared,
                                                                 const unsigned int  _paramIdx,
                                                                 const int           _variationIdx
                                                                 ) {
   ST_PLUGIN_SHARED_CAST(modular_env_analog_1_shared_t);
   switch(_paramIdx)
   {
      default:
         break;
   }
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static const char *ST_PLUGIN_API loc_get_array_param_element_name(st_plugin_info_t   *_info,
                                                                  const unsigned int  _paramIdx,
                                                                  const unsigned int  _elementIdx
                                                                  ) {
   ST_PLUGIN_INFO_CAST(modular_env_analog_1_info_t);
   const char *r = NULL;
   switch(_paramIdx)
   {
      default:
         break;
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static int ST_PLUGIN_API loc_get_array_param_element_value_range(st_plugin_info_t   *_info,
                                                                 const unsigned int  _paramIdx,
                                                                 const unsigned int  _elementIdx,
                                                                 float              *_retStorageMin,
                                                                 float              *_retStorageMax,
                                                                 float              *_retDisplayMin,
                                                                 float              *_retDisplayMax,
                                                                 unsigned int       *_retDisplayPrecision
                                                                 ) {
   (void)_elementIdx;
   switch(_paramIdx)
   {
      default:
         break;
   }
   return 0;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static float ST_PLUGIN_API loc_get_array_param_element_reset(st_plugin_info_t   *_info,
                                                             const unsigned int  _paramIdx,
                                                             const unsigned int  _elementIdx
                                                             ) {
   ST_PLUGIN_INFO_CAST(modular_env_analog_1_info_t);
   float r = -999999.0f/*INVALID_VALUE*/;
   switch(_paramIdx)
   {
      default:
         break;
   }
   return r;
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static void ST_PLUGIN_API loc_update_lut(st_plugin_info_t   *_info,
                                         unsigned int        _idx,
                                         const float        *_src,
                                         const unsigned int  _srcNumElements
                                         ) {
   (void)_info;
   unsigned int copySz = 0u;
   (void)copySz;
   switch(_idx)
   {
      default:
         break;
      case 0: // "shape"
         copySz = Dstplugin_min(_srcNumElements, 4096);
         for(unsigned int i = 0u; i < copySz; i++)
            curve_0[i] = (short)(_src[i] * 2048);
         break;
   }
}
#endif // CYCLE_SKIP_UI

#ifndef CYCLE_SKIP_UI
static const char *ST_PLUGIN_API loc_get_mod_name(st_plugin_info_t *_info,
                                                  unsigned int      _modIdx
                                                  ) {
   (void)_info;
   return loc_mod_names[_modIdx];
}
#endif // CYCLE_SKIP_UI

static void ST_PLUGIN_API loc_set_sample_rate(st_plugin_voice_t *_voice,
                                              float              _sampleRate
                                              ) {
   ST_PLUGIN_VOICE_CAST(modular_env_analog_1_voice_t);
   if(_sampleRate != voice->sample_rate)
   {
      voice->sr_factor = 48000.0f / _sampleRate;
      voice->add_sr_0 = voice->sr_factor * 0.03f;
   }
   voice->sample_rate = _sampleRate;
}

static void ST_PLUGIN_API loc_set_bpm(st_plugin_voice_t *_voice,
                                      float              _bpm
                                      ) {
   ST_PLUGIN_VOICE_CAST(modular_env_analog_1_voice_t);
   voice->bpm = _bpm;
}

static void ST_PLUGIN_API loc_note_on(st_plugin_voice_t  *_voice,
                                      int                 _bGlide,
                                      unsigned char       _note,
                                      float               _vel
                                      ) {
   ST_PLUGIN_VOICE_CAST(modular_env_analog_1_voice_t);
   ST_PLUGIN_VOICE_SHARED_CAST(modular_env_analog_1_shared_t);
   (void)_bGlide;
   (void)_note;
   (void)_vel;
   if(!_bGlide)
   {
      memset((void*)voice->mods, 0, sizeof(voice->mods));
#ifdef OVERSAMPLE_FACTOR
      voice->note_speed_fixed = (261.63f/*C-5*/ / (voice->sample_rate * OVERSAMPLE_FACTOR));
#else
      voice->note_speed_fixed = (261.63f/*C-5*/ / voice->sample_rate);
#endif // OVERSAMPLE_FACTOR
      voice->velocity = _vel;
      voice->tmp1_adsrv1_last_gate = 0.0f;
      voice->tmp7_adsrv1_segidx = 4;
      voice->var_x = 0.0f;
   }
}

static void ST_PLUGIN_API loc_set_mod_value(st_plugin_voice_t *_voice,
                                            unsigned int       _modIdx,
                                            float              _value,
                                            unsigned           _frameOffset
                                            ) {
   ST_PLUGIN_VOICE_CAST(modular_env_analog_1_voice_t);
   (void)_frameOffset;
   voice->mods[_modIdx] = _value;
}

static void ST_PLUGIN_API loc_prepare_block(st_plugin_voice_t *_voice,
                                            unsigned int       _numFrames,
                                            float              _freqHz,
                                            float              _note,
                                            float              _vol,
                                            float              _pan
                                            ) {
   ST_PLUGIN_VOICE_CAST(modular_env_analog_1_voice_t);
   ST_PLUGIN_VOICE_SHARED_CAST(modular_env_analog_1_shared_t);
   (void)_note;
   (void)_vol;
   (void)_pan;

#ifdef OVERSAMPLE_FACTOR
   float noteSpeed = _freqHz / (voice->sample_rate * OVERSAMPLE_FACTOR);
#else
   float noteSpeed = _freqHz / voice->sample_rate;
#endif // OVERSAMPLE_FACTOR

   float modgate         = voice->mods[MOD_GATE         ];
   float moda            = shared->params[PARAM_A           ]                       + voice->mods[MOD_A            ];
   float modashape       = shared->params[PARAM_ASHAPE      ]                       + voice->mods[MOD_ASHAPE       ];
   float modd            = shared->params[PARAM_D           ]                       + voice->mods[MOD_D            ];
   float mods            = shared->params[PARAM_S           ]                       + voice->mods[MOD_S            ];
   float modr            = shared->params[PARAM_R           ]                       + voice->mods[MOD_R            ];
   float moddr_shape     = voice->mods[MOD_DR_SHAPE     ];
   float modshape_amt    = shared->params[PARAM_SHAPE_AMT   ]                       + voice->mods[MOD_SHAPE_AMT    ];

   if(_numFrames > 0u)
   {
      // lerp
#ifdef OVERSAMPLE_FACTOR
      float recBlockSize = (1.0f / (_numFrames * OVERSAMPLE_FACTOR));
#else
      float recBlockSize = (1.0f / _numFrames);
#endif // OVERSAMPLE_FACTOR
      voice->note_speed_inc = (noteSpeed - voice->note_speed_cur) * recBlockSize;
      voice->note_inc       = (_note - voice->note_cur) * recBlockSize;
      voice->mod_gate_inc         = (modgate            - voice->mod_gate_cur          ) * recBlockSize;
      voice->mod_a_inc            = (moda               - voice->mod_a_cur             ) * recBlockSize;
      voice->mod_ashape_inc       = (modashape          - voice->mod_ashape_cur        ) * recBlockSize;
      voice->mod_d_inc            = (modd               - voice->mod_d_cur             ) * recBlockSize;
      voice->mod_s_inc            = (mods               - voice->mod_s_cur             ) * recBlockSize;
      voice->mod_r_inc            = (modr               - voice->mod_r_cur             ) * recBlockSize;
      voice->mod_dr_shape_inc     = (moddr_shape        - voice->mod_dr_shape_cur      ) * recBlockSize;
      voice->mod_shape_amt_inc    = (modshape_amt       - voice->mod_shape_amt_cur     ) * recBlockSize;
   }
   else
   {
      // initial params/modulation (first block, not rendered)
      voice->note_speed_cur = noteSpeed;
      voice->note_speed_inc = 0.0f;
      voice->note_cur       = _note;
      voice->note_inc       = 0.0f;
      voice->mod_gate_cur         = modgate;
      voice->mod_gate_inc         = 0.0f;
      voice->mod_a_cur            = moda;
      voice->mod_a_inc            = 0.0f;
      voice->mod_ashape_cur       = modashape;
      voice->mod_ashape_inc       = 0.0f;
      voice->mod_d_cur            = modd;
      voice->mod_d_inc            = 0.0f;
      voice->mod_s_cur            = mods;
      voice->mod_s_inc            = 0.0f;
      voice->mod_r_cur            = modr;
      voice->mod_r_inc            = 0.0f;
      voice->mod_dr_shape_cur     = moddr_shape;
      voice->mod_dr_shape_inc     = 0.0f;
      voice->mod_shape_amt_cur    = modshape_amt;
      voice->mod_shape_amt_inc    = 0.0f;
   }

   // printf("xxx note_cur=%f\n", voice->note_cur);
   // printf("xxx prepare_block: numFrames=%u moda=%f\n", _numFrames, moda);
   // printf("xxx voice->voicebus_idx_0=%u voice->base.voice_bus_read_offset=%u\n", voice->voicebus_idx_0, voice->base.voice_bus_read_offset);
}

static void ST_PLUGIN_API loc_process_replace(st_plugin_voice_t  *_voice,
                                              int                 _bMonoIn,
                                              const float        *_samplesIn,
                                              float              *_samplesOut,
                                              unsigned int        _numFrames
                                              ) {
   (void)_bMonoIn;
   (void)_samplesIn;

   ST_PLUGIN_VOICE_CAST(modular_env_analog_1_voice_t);
   ST_PLUGIN_VOICE_SHARED_CAST(modular_env_analog_1_shared_t);

   // Mono output (replicate left to right channel)
   unsigned int j = 0u;
#ifndef STEREO
   unsigned int jStep = _bMonoIn ? 1u : 2u;
#endif // STEREO
   unsigned int k = 0u;
   for(unsigned int i = 0u; i < _numFrames; i++)
   {
      const float inL = _samplesIn[j];
#ifdef STEREO
      float outL;
      float outR;
      const float inR = _samplesIn[j + 1u];
#endif // STEREO
      float out;
#ifdef OVERSAMPLE_FACTOR
#ifdef STEREO
      float outOSL = 0.0f;
      float outOSR = 0.0f;
#else
      float outOS = 0.0f;
#endif // STEREO
#endif // OVERSAMPLE_FACTOR

#ifdef OVERSAMPLE_FACTOR
      for(unsigned int osi = 0u; osi < OVERSAMPLE_FACTOR; osi++)
#endif // OVERSAMPLE_FACTOR
      {
#ifdef STEREO
         out = outL = inL;
         outR = inR;
#else
         out = inL;
#endif // STEREO
      float tmp_f;
      float tmp2_f;
      
      // ========
      // ======== lane "out" modIdx=0 class=$m_gate
      // ========
      
      // -- mod="$m_gate" dstVar=out
      out = voice->mod_gate_cur;
      
      // -- mod="adsr" dstVar=out
      
      // ---- mod="adsr" input "s" seq 1/1
      
      // -- mod="$m_s" dstVar=voice->tmp9/*adsrv1_suslvl*/
      voice->tmp9/*adsrv1_suslvl*/ = voice->mod_s_cur;
      if(out > 0.001f && voice->tmp1_adsrv1_last_gate <= 0.001f)
      {
         voice->tmp4_adsrv1_vel = out;
         voice->tmp6_adsrv1_last_atk_level = voice->tmp2_adsrv1_levelint;
         voice->tmp7_adsrv1_segidx = 0;
         voice->tmp1_adsrv1_last_gate = 1.0f;
      }
      else if(out <= 0.001f && voice->tmp1_adsrv1_last_gate > 0.001f)
      {
         voice->tmp7_adsrv1_segidx = 3;
         voice->tmp1_adsrv1_last_gate = 0.0f;
         voice->tmp2_adsrv1_levelint = voice->tmp3_adsrv1_level;
         voice->tmp5_adsrv1_last_sus_level = voice->tmp3_adsrv1_level;
      }
      switch(voice->tmp7_adsrv1_segidx)
      {
         case 0: // a
            
            // ---- mod="adsr" input "a" seq 1/1
            
            // -- mod="$m_a" dstVar=voice->tmp8/*adsrv1_rate*/
            voice->tmp8/*adsrv1_rate*/ = voice->mod_a_cur;
            
            // -- mod="clp" dstVar=voice->tmp8/*adsrv1_rate*/
            if(voice->tmp8/*adsrv1_rate*/ > 1.0f) voice->tmp8/*adsrv1_rate*/ = 1.0f;
            else if(voice->tmp8/*adsrv1_rate*/ < 0.0f) voice->tmp8/*adsrv1_rate*/ = 0.0f;
            
            // -- mod="pow" dstVar=voice->tmp8/*adsrv1_rate*/
            voice->tmp8/*adsrv1_rate*/ = voice->tmp8/*adsrv1_rate*/ * voice->tmp8/*adsrv1_rate*/ * voice->tmp8/*adsrv1_rate*/;
            voice->tmp2_adsrv1_levelint += voice->tmp8/*adsrv1_rate*/ * voice->add_sr_0;
            if(voice->tmp2_adsrv1_levelint >= 1.0f)
            {
               voice->tmp3_adsrv1_level = 1.0f;
               voice->tmp2_adsrv1_levelint = 1.0f;
               voice->tmp7_adsrv1_segidx++;
            }
            else
            {
               voice->tmp10/*adsrv1_delta_h*/ = (voice->tmp2_adsrv1_levelint - voice->tmp6_adsrv1_last_atk_level);
               voice->tmp11/*adsrv1_delta_n*/ = (1.0f != voice->tmp6_adsrv1_last_atk_level) ? (voice->tmp10/*adsrv1_delta_h*/ / (1.0f - voice->tmp6_adsrv1_last_atk_level)) : voice->tmp10/*adsrv1_delta_h*/;
               
               // ---- mod="adsr" input "as" seq 1/1
               
               // -- mod="$m_ashape" dstVar=voice->tmp12/*adsrv1_ashape_c*/
               voice->tmp12/*adsrv1_ashape_c*/ = voice->mod_ashape_cur;
               
               // -- mod="fma" dstVar=voice->tmp12/*adsrv1_ashape_c*/
               voice->tmp12/*adsrv1_ashape_c*/ = (voice->tmp12/*adsrv1_ashape_c*/ * 16.0f) + -8.0f;
               voice->tmp11/*adsrv1_delta_n*/ = mathLogLinExpf(voice->tmp11/*adsrv1_delta_n*/, voice->tmp12/*adsrv1_ashape_c*/);
               voice->tmp3_adsrv1_level = voice->tmp6_adsrv1_last_atk_level + voice->tmp11/*adsrv1_delta_n*/ * voice->tmp10/*adsrv1_delta_h*/;
            }
            break;
      
         case 1: // d
            
            // ---- mod="adsr" input "d" seq 1/1
            
            // -- mod="$m_d" dstVar=voice->tmp8/*adsrv1_rate*/
            voice->tmp8/*adsrv1_rate*/ = voice->mod_d_cur;
            
            // -- mod="clp" dstVar=voice->tmp8/*adsrv1_rate*/
            if(voice->tmp8/*adsrv1_rate*/ > 1.0f) voice->tmp8/*adsrv1_rate*/ = 1.0f;
            else if(voice->tmp8/*adsrv1_rate*/ < 0.0f) voice->tmp8/*adsrv1_rate*/ = 0.0f;
            
            // -- mod="pow" dstVar=voice->tmp8/*adsrv1_rate*/
            voice->tmp8/*adsrv1_rate*/ = voice->tmp8/*adsrv1_rate*/ * voice->tmp8/*adsrv1_rate*/ * voice->tmp8/*adsrv1_rate*/;
            voice->tmp2_adsrv1_levelint -= voice->tmp8/*adsrv1_rate*/ * voice->add_sr_0;
            if(voice->tmp2_adsrv1_levelint <= voice->tmp9/*adsrv1_suslvl*/)
            {
               voice->tmp3_adsrv1_level = voice->tmp9/*adsrv1_suslvl*/;
               voice->tmp2_adsrv1_levelint = voice->tmp9/*adsrv1_suslvl*/;
               voice->tmp7_adsrv1_segidx++;
            }
            else
            {
               voice->tmp10/*adsrv1_delta_h*/ = (voice->tmp2_adsrv1_levelint - voice->tmp9/*adsrv1_suslvl*/);
               voice->tmp11/*adsrv1_delta_n*/ = (1.0f != voice->tmp9/*adsrv1_suslvl*/) ? (voice->tmp10/*adsrv1_delta_h*/ / (1.0f - voice->tmp9/*adsrv1_suslvl*/)) : voice->tmp10/*adsrv1_delta_h*/;
               
               // ---- mod="adsr" input "ds" seq 1/1
               
               // -- mod="$p_dshape" dstVar=voice->tmp12/*adsrv1_dshape_c*/
               voice->tmp12/*adsrv1_dshape_c*/ = shared->params[PARAM_DSHAPE];
               
               // -- mod="$m_dr_shape" dstVar=voice->tmp12/*adsrv1_dshape_c*/
               voice->tmp13/*seq*/ = voice->mod_dr_shape_cur;
               voice->tmp12/*adsrv1_dshape_c*/ += voice->tmp13/*seq*/;
               
               // -- mod="fma" dstVar=voice->tmp12/*adsrv1_dshape_c*/
               voice->tmp12/*adsrv1_dshape_c*/ = (voice->tmp12/*adsrv1_dshape_c*/ * 16.0f) + -8.0f;
               voice->tmp11/*adsrv1_delta_n*/ = mathLogLinExpf(voice->tmp11/*adsrv1_delta_n*/, voice->tmp12/*adsrv1_dshape_c*/);
               voice->tmp3_adsrv1_level = voice->tmp9/*adsrv1_suslvl*/ + voice->tmp11/*adsrv1_delta_n*/ * voice->tmp10/*adsrv1_delta_h*/;
            }
            break;
      
         case 2: // s
            voice->tmp3_adsrv1_level = voice->tmp9/*adsrv1_suslvl*/;
            break;
      
         case 3: // r
            
            // ---- mod="adsr" input "r" seq 1/1
            
            // -- mod="$m_r" dstVar=voice->tmp8/*adsrv1_rate*/
            voice->tmp8/*adsrv1_rate*/ = voice->mod_r_cur;
            
            // -- mod="clp" dstVar=voice->tmp8/*adsrv1_rate*/
            if(voice->tmp8/*adsrv1_rate*/ > 1.0f) voice->tmp8/*adsrv1_rate*/ = 1.0f;
            else if(voice->tmp8/*adsrv1_rate*/ < 0.0f) voice->tmp8/*adsrv1_rate*/ = 0.0f;
            
            // -- mod="pow" dstVar=voice->tmp8/*adsrv1_rate*/
            voice->tmp8/*adsrv1_rate*/ = voice->tmp8/*adsrv1_rate*/ * voice->tmp8/*adsrv1_rate*/ * voice->tmp8/*adsrv1_rate*/;
            voice->tmp2_adsrv1_levelint -= voice->tmp8/*adsrv1_rate*/ * voice->add_sr_0;
            if(voice->tmp2_adsrv1_levelint <= 0.0f)
            {
               voice->tmp3_adsrv1_level = 0.0f;
               voice->tmp2_adsrv1_levelint = 0.0f;
               voice->tmp7_adsrv1_segidx++;
            }
               voice->tmp10/*adsrv1_delta_h*/ = (voice->tmp2_adsrv1_levelint/* - 0.0f*/);
               voice->tmp11/*adsrv1_delta_n*/ = (0.0f != voice->tmp5_adsrv1_last_sus_level) ? (voice->tmp10/*adsrv1_delta_h*/ / voice->tmp5_adsrv1_last_sus_level) : voice->tmp10/*adsrv1_delta_h*/;
               
               // ---- mod="adsr" input "rs" seq 1/1
               
               // -- mod="$p_rshape" dstVar=voice->tmp12/*adsrv1_rshape_c*/
               voice->tmp12/*adsrv1_rshape_c*/ = shared->params[PARAM_RSHAPE];
               
               // -- mod="$m_dr_shape" dstVar=voice->tmp12/*adsrv1_rshape_c*/
               voice->tmp13/*seq*/ = voice->mod_dr_shape_cur;
               voice->tmp12/*adsrv1_rshape_c*/ += voice->tmp13/*seq*/;
               
               // -- mod="fma" dstVar=voice->tmp12/*adsrv1_rshape_c*/
               voice->tmp12/*adsrv1_rshape_c*/ = (voice->tmp12/*adsrv1_rshape_c*/ * 16.0f) + -8.0f;
               voice->tmp11/*adsrv1_delta_n*/ = mathLogLinExpf(voice->tmp11/*adsrv1_delta_n*/, voice->tmp12/*adsrv1_rshape_c*/);
               voice->tmp3_adsrv1_level = voice->tmp11/*adsrv1_delta_n*/ * voice->tmp10/*adsrv1_delta_h*/;
            break;
      
         default:
         case 4: // <end>
            break;
      }
      out = voice->tmp3_adsrv1_level * voice->tmp4_adsrv1_vel;
      
      // -- mod="ipl" dstVar=out
      voice->tmp8/*b*/ = out;
      
      // ---- mod="ipl" input "b" seq 1/1
      
      // -- mod="lut" dstVar=voice->tmp8/*b*/
      voice->tmp9/*lut_f*/ = (voice->tmp8/*b*/ * 4096);
      voice->tmp10/*lut_frac*/ = voice->tmp9/*lut_f*/ - (int)voice->tmp9/*lut_f*/;
      voice->tmp14/*lut_idx_a*/ = (int)voice->tmp9/*lut_f*/;
      if(voice->tmp14/*lut_idx_a*/ < 0)
      {
         voice->tmp14/*lut_idx_a*/ = 0;
         voice->tmp15/*lut_idx_b*/ = 0;
         voice->tmp10/*lut_frac*/ = 0.0f;
      }
      else if(voice->tmp14/*lut_idx_a*/ > 4095)
      {
         voice->tmp14/*lut_idx_a*/ = 4095;
         voice->tmp15/*lut_idx_b*/ = 4095;
      }
      else
      {
         voice->tmp15/*lut_idx_b*/ = voice->tmp14/*lut_idx_a*/ + 1;
         if(voice->tmp15/*lut_idx_b*/ > 4095)
            voice->tmp15/*lut_idx_b*/ = 4095;
      }
      voice->tmp11/*lut_a*/ = curve_0[(unsigned int)voice->tmp14/*lut_idx_a*/] * (1.0f / 2048);
      voice->tmp12/*lut_b*/ = curve_0[(unsigned int)voice->tmp15/*lut_idx_b*/] * (1.0f / 2048);
      voice->tmp8/*b*/ = voice->tmp11/*lut_a*/ + (voice->tmp12/*lut_b*/ - voice->tmp11/*lut_a*/) * voice->tmp10/*lut_frac*/;
      voice->tmp9/*t*/ = out;
      
      // ---- mod="ipl" input "t" seq 1/1
      
      // -- mod="$m_shape_amt" dstVar=voice->tmp9/*t*/
      voice->tmp9/*t*/ = voice->mod_shape_amt_cur;
      out = out + (voice->tmp8/*b*/ - out) * voice->tmp9/*t*/;

      /* end calc */

#ifdef OVERSAMPLE_FACTOR
#ifdef STEREO
         outOSL += outL;
         outOSR += outR;
#else
         outOS += out;
#endif // STEREO
#endif // OVERSAMPLE_FACTOR
         voice->note_speed_cur += voice->note_speed_inc;
         voice->note_cur       += voice->note_inc;
         voice->mod_gate_cur       += voice->mod_gate_inc;
         voice->mod_a_cur          += voice->mod_a_inc;
         voice->mod_ashape_cur     += voice->mod_ashape_inc;
         voice->mod_d_cur          += voice->mod_d_inc;
         voice->mod_s_cur          += voice->mod_s_inc;
         voice->mod_r_cur          += voice->mod_r_inc;
         voice->mod_dr_shape_cur   += voice->mod_dr_shape_inc;
         voice->mod_shape_amt_cur  += voice->mod_shape_amt_inc;
      }
#ifdef OVERSAMPLE_FACTOR
      // Apply lowpass filter before downsampling
      //   (note) normalized Fc = F/Fs = 0.442947 / sqrt(oversample_factor^2 - 1)
#ifdef STEREO
      outL = outOSL * (1.0f / OVERSAMPLE_FACTOR);
      outR = outOSR * (1.0f / OVERSAMPLE_FACTOR);
#else
      out = outOS * (1.0f / OVERSAMPLE_FACTOR);
#endif // STEREO
#endif // OVERSAMPLE_FACTOR
#ifdef STEREO
      outL = Dstplugin_fix_denorm_32(outL);
      outR = Dstplugin_fix_denorm_32(outR);
#else
      out = Dstplugin_fix_denorm_32(out);
#endif // STEREO
#ifdef STEREO
      _samplesOut[k]      = outL;
      _samplesOut[k + 1u] = outR;
#else
      _samplesOut[k]      = out;
      _samplesOut[k + 1u] = out;
#endif // STEREO

      // Next frame
      k += 2u;
#ifdef STEREO
      j += 2u;
#else
      j += jStep;
#endif // STEREO
   } /* loop numFrames */
}

static st_plugin_shared_t *ST_PLUGIN_API loc_shared_new(st_plugin_info_t *_info) {
   modular_env_analog_1_shared_t *ret = (modular_env_analog_1_shared_t *)malloc(sizeof(modular_env_analog_1_shared_t));
   if(NULL != ret)
   {
      memset((void*)ret, 0, sizeof(*ret));
      ret->base.info  = _info;
      memcpy((void*)ret->params, (void*)loc_param_resets, NUM_PARAMS * sizeof(float));
   }
   return &ret->base;
}

static void ST_PLUGIN_API loc_shared_delete(st_plugin_shared_t *_shared) {
   free((void*)_shared);
}

static st_plugin_voice_t *ST_PLUGIN_API loc_voice_new(st_plugin_info_t *_info, unsigned int _voiceIdx) {
   modular_env_analog_1_voice_t *voice = (modular_env_analog_1_voice_t *)malloc(sizeof(modular_env_analog_1_voice_t));
   if(NULL != voice)
   {
      memset((void*)voice, 0, sizeof(*voice));
      voice->base.info = _info;
      voice->tmp2_adsrv1_levelint = 0.0f;
      voice->tmp3_adsrv1_level = 0.0f;
      voice->tmp4_adsrv1_vel = 0.0f;
      voice->tmp5_adsrv1_last_sus_level = 0.0f;
      voice->tmp6_adsrv1_last_atk_level = 0.0f;
   }
   return &voice->base;
}

static void ST_PLUGIN_API loc_voice_delete(st_plugin_voice_t *_voice) {
   ST_PLUGIN_VOICE_CAST(modular_env_analog_1_voice_t);

   free((void*)_voice);
   }

static void ST_PLUGIN_API loc_plugin_exit(st_plugin_info_t *_info) {
   free((void*)_info);
}

#ifdef USE_CYCLE_SINE_TBL
static void loc_calc_sine_tbl(void) {
#define QCOS_BITS 16
#define QCOS_ONE  (1 << QCOS_BITS)
#define QCOS_MASK (QCOS_ONE - 1)
   // (note) same as in TSR "C" implementation
   float *qcos = cycle_sine_tbl_f + 4096; // quarter cos tbl

   // calc quarter cos tbl
   int k = 0;
   for(int a = 0; a < (QCOS_ONE/4); a += (QCOS_ONE/16384)/*4*/)  // 4096 elements
   {
      int x = a - ((int)(QCOS_ONE * 0.25 + 0.5)) + ((a + ((int)(QCOS_ONE * 0.25 + 0.5)))&~QCOS_MASK);
      x = ((x * ((x<0?-x:x) - ((int)(QCOS_ONE * 0.5 + 0.5)))) >> QCOS_BITS) << 4;
      x += (((((int)(QCOS_ONE * 0.225 + 0.5)) * x) >> QCOS_BITS) * ((x<0?-x:x) - QCOS_ONE)) >> QCOS_BITS;
      qcos[k++] = x / float(QCOS_ONE);
   }

   // 0°..90° (rev qtbl)
   int j = 4096;
   k = 0;
   loop(4096)
      cycle_sine_tbl_f[k++] = qcos[--j];

   // 90..180° = cos tbl
   k += 4096;

   // 180°..360° (y-flip first half of tbl)
   j = 0;
   loop(8192)
      cycle_sine_tbl_f[k++] = -cycle_sine_tbl_f[j++];

#ifdef USE_CYCLE_SINE_TBL_I
   loop(16384)
      cycle_sine_tbl_i[i] = (short)(cycle_sine_tbl_f[i] * 2048.0f/*FX_ONE*/);
#endif // USE_CYCLE_SINE_TBL_I
}
#endif // USE_CYCLE_SINE_TBL

#ifdef USE_CYCLE_HSE_TBL
#endif // USE_CYCLE_HSE_TBL

extern "C" {
st_plugin_info_t *modular_env_analog_1_init(void) {
   modular_env_analog_1_info_t *ret = (modular_env_analog_1_info_t *)malloc(sizeof(modular_env_analog_1_info_t));

   if(NULL != ret)
   {
      memset(ret, 0, sizeof(*ret));

      ret->base.api_version = ST_PLUGIN_API_VERSION;
      ret->base.id          = "modular_env_analog_1";  // unique id. don't change this in future builds.
      // (note) don't set author/name/short_name when CYCLE_SKIP_UI is defined ?
      ret->base.author      = "bsp";
      ret->base.name        = "modular_env_analog_1";
      ret->base.short_name  = "modular_env_analog_1";
      ret->base.flags       = ST_PLUGIN_FLAG_FX;
      ret->base.category    = ST_PLUGIN_CAT_AMP;
      ret->base.num_params  = NUM_PARAMS;
      ret->base.num_mods    = NUM_MODS;

      ret->base.shared_new                          = &loc_shared_new;
      ret->base.shared_delete                       = &loc_shared_delete;
      ret->base.voice_new                           = &loc_voice_new;
      ret->base.voice_delete                        = &loc_voice_delete;
#ifndef CYCLE_SKIP_UI
      ret->base.get_param_name                      = &loc_get_param_name;
      ret->base.get_param_group_name                = &loc_get_param_group_name;
      ret->base.get_param_group_idx                 = &loc_get_param_group_idx;
      ret->base.get_param_section_name              = &loc_get_param_section_name;
      ret->base.get_param_section_idx               = &loc_get_param_section_idx;
      ret->base.get_param_reset                     = &loc_get_param_reset;
      ret->base.query_dynamic_param_preset_values   = &loc_query_dynamic_param_preset_values;
      ret->base.query_dynamic_param_preset_name     = &loc_query_dynamic_param_preset_name;
      ret->base.get_array_param_size                = &loc_get_array_param_size;
      ret->base.get_array_param_num_variations      = &loc_get_array_param_num_variations;
      ret->base.get_array_param_variation_ptr       = &loc_get_array_param_variation_ptr;
      ret->base.set_array_param_edit_variation_idx  = &loc_set_array_param_edit_variation_idx;
      ret->base.get_array_param_element_name        = &loc_get_array_param_element_name;
      ret->base.get_array_param_element_value_range = &loc_get_array_param_element_value_range;
      ret->base.get_array_param_element_reset       = &loc_get_array_param_element_reset;
      ret->base.update_lut                          = &loc_update_lut;
#endif // CYCLE_SKIP_UI
      ret->base.get_param_value                     = &loc_get_param_value;
      ret->base.set_param_value                     = &loc_set_param_value;
#ifndef CYCLE_SKIP_UI
      ret->base.get_mod_name                        = &loc_get_mod_name;
#endif // CYCLE_SKIP_UI
      ret->base.set_sample_rate                     = &loc_set_sample_rate;
      ret->base.set_bpm                             = &loc_set_bpm;
      ret->base.note_on                             = &loc_note_on;
      ret->base.set_mod_value                       = &loc_set_mod_value;
      ret->base.prepare_block                       = &loc_prepare_block;
      ret->base.process_replace                     = &loc_process_replace;
      ret->base.plugin_exit                         = &loc_plugin_exit;

#ifdef USE_CYCLE_SINE_TBL
      loc_calc_sine_tbl();
#endif // USE_CYCLE_SINE_TBL
   }

   return &ret->base;
}

#ifndef STFX_SKIP_MAIN_INIT
ST_PLUGIN_APICALL st_plugin_info_t *ST_PLUGIN_API st_plugin_init(unsigned int _pluginIdx) {
   switch(_pluginIdx)
   {
      case 0u:
         return modular_env_analog_1_init();
   }
   return NULL;
}
#endif // STFX_SKIP_MAIN_INIT

} // extern "C"
